local bufnr = vim.api.nvim_get_current_buf()
local map = vim.keymap.set

map("n", "K", function()
  vim.cmd.RustLsp({ "hover", "actions" })
end, { buffer = bufnr, silent = true, desc = "Rust hover actions" })

map("n", "gd", vim.lsp.buf.definition, { buffer = bufnr, silent = true, desc = "Go to definition" })
map("n", "gr", vim.lsp.buf.references, { buffer = bufnr, silent = true, desc = "References" })
map("n", "<leader>ca", function()
  vim.cmd.RustLsp("codeAction")
end, { buffer = bufnr, silent = true, desc = "Rust code action" })

map("n", "<leader>rr", '<cmd>TermExec cmd="cargo run"<cr>', { buffer = bufnr, silent = true, desc = "Cargo run" })
map("n", "<leader>rt", '<cmd>TermExec cmd="cargo test"<cr>', { buffer = bufnr, silent = true, desc = "Cargo test" })
map("n", "<leader>rc", '<cmd>TermExec cmd="cargo check"<cr>', { buffer = bufnr, silent = true, desc = "Cargo check" })
map("n", "<leader>rl", '<cmd>TermExec cmd="cargo clippy"<cr>', { buffer = bufnr, silent = true, desc = "Cargo clippy" })

map("n", "<leader>dd", function()
  require("dap").continue()
end, { buffer = bufnr, silent = true, desc = "DAP continue" })
map("n", "<leader>db", function()
  require("dap").toggle_breakpoint()
end, { buffer = bufnr, silent = true, desc = "DAP breakpoint" })
map("n", "<leader>do", function()
  require("dap").step_over()
end, { buffer = bufnr, silent = true, desc = "DAP step over" })
map("n", "<leader>di", function()
  require("dap").step_into()
end, { buffer = bufnr, silent = true, desc = "DAP step into" })
map("n", "<leader>dO", function()
  require("dap").step_out()
end, { buffer = bufnr, silent = true, desc = "DAP step out" })
map("n", "<leader>du", function()
  require("dapui").toggle()
end, { buffer = bufnr, silent = true, desc = "DAP UI toggle" })
